import { MD3LightTheme, MD3DarkTheme } from "react-native-paper";

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#1976d2",
    primaryContainer: "#e3f2fd",
    secondary: "#ff9800",
    secondaryContainer: "#fff3e0",
    tertiary: "#4caf50",
    tertiaryContainer: "#e8f5e8",
    surface: "#ffffff",
    surfaceVariant: "#f5f5f5",
    background: "#fafafa",
    error: "#d32f2f",
    errorContainer: "#ffebee",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#0d47a1",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#e65100",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#1b5e20",
    onSurface: "#212121",
    onSurfaceVariant: "#757575",
    onBackground: "#212121",
    onError: "#ffffff",
    onErrorContainer: "#b71c1c",
    outline: "#bdbdbd",
    outlineVariant: "#e0e0e0",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#303030",
    inverseOnSurface: "#fafafa",
    inversePrimary: "#90caf9",
    elevation: {
      ...MD3LightTheme.colors.elevation,
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#90caf9",
    primaryContainer: "#0d47a1",
    secondary: "#ffb74d",
    secondaryContainer: "#e65100",
    tertiary: "#81c784",
    tertiaryContainer: "#1b5e20",
    surface: "#121212",
    surfaceVariant: "#1e1e1e",
    background: "#000000",
    error: "#ef5350",
    errorContainer: "#b71c1c",
    onPrimary: "#0d47a1",
    onPrimaryContainer: "#e3f2fd",
    onSecondary: "#e65100",
    onSecondaryContainer: "#fff3e0",
    onTertiary: "#1b5e20",
    onTertiaryContainer: "#e8f5e8",
    onSurface: "#ffffff",
    onSurfaceVariant: "#cccccc",
    onBackground: "#ffffff",
    onError: "#ffffff",
    onErrorContainer: "#ffebee",
    outline: "#616161",
    outlineVariant: "#424242",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#fafafa",
    inverseOnSurface: "#303030",
    inversePrimary: "#1976d2",
    elevation: {
      ...MD3DarkTheme.colors.elevation,
    },
  },
};

// Default to light theme (you can add dark mode detection later)
export const theme = lightTheme;
